T/2: Initial implementation of Alignment feature
ckeditor/ckeditor5-alignment pull request #6
Opened 2017-11-03 07:26 UTC by jodator

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Initial implementation. Closes #2.

---

### Additional information

This PR comes with changes in other packages branches:
- https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-alignment/2 (introduced package + updated mgit.json for PR review).
- https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5-alignment/2 (removed icons)

Merge commit message for related branches:
- ckeditor5: `Feature: Introduce ckeditor5-alignment package.`
- ckeditor5-core: `Internal: Remove align icons from theme folder that are moved to ckeditor5-alignment plugin.`

Misc
* The initial implementation comes with 4 separate buttons due to missing split button UI component.
* at least two follow-ups are needed:
    - implementing split button #4,
    - update converters to use new helpers #5 as at the moment `style` attribute on view will be replaced if any other feature would also define to attribute `style` converter #5.

2017-11-06 12:43 UTC, szymonkups requested changes

2017-11-06 12:43 UTC, szymonkups commented on src/alignmentediting.js
> +	static get requires() {
Is it needed?

2017-11-06 12:43 UTC, szymonkups commented on src/alignmentcommand.js
> +	_isDefault() {
It is the same method as in `AligmentEditing` class. Maybe we could get rid of this duplicated code? We could pass this information in command's constructor or make it an utility function same as `isSupported`. WDYT?

2017-11-06 12:43 UTC, szymonkups commented on src/alignmentediting.js
> +		// Disallow alignment on fiqcaption
Ending dot missing.

2017-11-06 12:43 UTC, szymonkups commented on src/alignmentui.js
> +				label: t( upperFirst( style ) ),
`t()` function should be executed with strings directly. See how `ImageStyles` plugin deals with localization for [default styles](https://github.com/ckeditor/ckeditor5-image/blob/842358571ab1cb68eb0ad6514f022d65d2ddbbfb/src/imagestyle/imagestyleengine.js#L131-L141). I would propose to use "align" word in labels: "Align left", "Align right", "Align center" and "Justify".

2017-11-06 12:43 UTC, szymonkups commented on src/alignmentediting.js
> +	}
This disallows `alignment` attribute on all `caption` elements (not only those from images). I don't know if this is something wrong just want to point that out. We are assuming here that `caption` element will always be used in same context as in image feature.

2017-11-06 12:43 UTC, szymonkups commented on tests/alignmentcommand.js
> +		it( 'is false when selection is not block that has different alignment', () => {
"is false when selection is inside block that has different alignment" WDYT?

2017-11-06 12:43 UTC, szymonkups commented on tests/alignmentcommand.js
> +		it( 'is false when selection is not block that has different alignment', () => {
"is false when selection is inside block that has different alignment (default style)" WDYT?

2017-11-06 12:43 UTC, szymonkups commented on tests/alignmentcommand.js
> +		it( 'is true when selection is in block with commend type alignment', () => {
"commend" => "command"

2017-11-06 12:43 UTC, szymonkups commented on tests/alignmentcommand.js
> +			it( 'removes alignment from all selected blocks even if one has not alignment', () => {
"... if one has no alignment defined" ?

2017-11-06 12:43 UTC, szymonkups commented on tests/alignmentediting.js
> +		it( 'is disallowed on figcaption', () => {
This should check if it is disabled on `caption` elements in model.

2017-11-06 12:43 UTC, szymonkups commented on tests/manual/alignmentconfig.js
> +			'headings', 'bold', 'italic', 'link', 'alignLeft', 'alignRight', 'alignCenter', 'alignJustify', 'bulletedList', 'numberedList',
Adding `alignLeft` and `alignRight` buttons cause warrnings in the console as they're not present with this configuration.

2017-11-07 07:03 UTC, jodator commented on src/alignmentcommand.js
> +	_isDefault() {
I've made this as checking if command is default one will be a bit more complex with RTL support. But until we do not know everything how RTL support will be provided it's better to make this as we cannot predict what arguments `isDefault` would need.

I'd change that.

2017-11-07 07:10 UTC, jodator commented on src/alignmentediting.js
> +	}
The only other element that could have (and probably will have) caption [is table](https://developer.mozilla.org/pl/docs/Web/HTML/Element/caption).

Probably it's name will be problematic as it may be confused with `figcaption` ;)

Anyway I suspect that Alignment feature would be disallowed there as in `<figcaption>` so probably such `disallow()` is OK.

2017-11-07 13:00 UTC, szymonkups commented
One bug spotted: when you select all content in `ckeditor5-alignment/tests/manual/alignment.html` manual test and change alignment, image caption changes it's alignment too. It is happening like that because there is no schema checking for each block in the selection when command is applied.

2017-11-07 13:35 UTC, szymonkups approved these changes

2017-11-07 13:38 UTC, merged